/*
 * common.h
 *
 * Created: 15.11.2017 0:13:14
 *  Author: Eugene
 */ 
#ifndef COMMON_H
#define COMMON_H

#include <stdint.h>

#define MILLISECONDS_IN_SIDERAL_DAY 86164000 // 86164.09054 seconds
#define ANGLE_MILLISECONDS_IN_CIRCLE 1296000000 // 360 * 60 * 60 * 1000

// #define ANGLE_MILLISECONDS_FOR_MOUNT_STEP (ANGLE_MILLISECONDS_IN_CIRCLE / STEPS_PER_ROUND / TRANSMISSION_RATE)
// #define STEPS_PER_FULL_ROUND ANGLE_MILLISECONDS_IN_CIRCLE / ANGLE_MILLISECONDS_FOR_MOUNT_STEP
#define STEP_TIME_IN_MILLIS(TRANSMISSION_RATE) (MILLISECONDS_IN_SIDERAL_DAY / TRANSMISSION_RATE )

#endif COMMON_H
